import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { translations } from './i18n/translations';

const STORAGE_KEY = 'ipm_user_preferences';

// Languages that are bundled directly in translations.js (high-quality manual translations)
const BUNDLED_LANGS = new Set(['en', 'es', 'fr', 'ar']);

function getStoredLanguage() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      const parsed = JSON.parse(stored);
      if (parsed.language) return parsed.language;
    }
  } catch (e) { /* ignore */ }
  return 'en';
}

const resources = {
  en: { translation: translations.en },
  es: { translation: translations.es },
  fr: { translation: translations.fr },
  ar: { translation: translations.ar },
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: getStoredLanguage(),
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false,
    },
    react: {
      useSuspense: false,
    },
  });

/**
 * Dynamically load a JSON translation bundle for auto-translated languages
 * (de, nl, pt, it, zh, ja, tr, ru, hi) from src/i18n/locales/<lang>.json.
 * The JSON files are generated by running: node scripts/generate-translations.mjs
 */
async function loadDynamicBundle(lang) {
  if (BUNDLED_LANGS.has(lang)) return; // already loaded
  if (i18n.hasResourceBundle(lang, 'translation')) return; // already added

  try {
    const bundle = await import(`./i18n/locales/${lang}.json`);
    i18n.addResourceBundle(lang, 'translation', bundle.default || bundle, false, false);
    // addResourceBundle doesn't automatically re-render react-i18next hooks.
    // Emitting languageChanged notifies all useTranslation() subscribers so
    // components re-render with the newly loaded translations immediately,
    // instead of staying on the English fallback until the next re-render trigger.
    if (i18n.language === lang) {
      i18n.emit('languageChanged', lang);
    }
  } catch (e) {
    // File not generated yet — silently fall back to English via fallbackLng
    console.warn(`[i18n] No bundle found for "${lang}", falling back to English.`);
  }
}

// Pre-load the stored language on startup (if it's a dynamic language)
const storedLang = getStoredLanguage();
if (!BUNDLED_LANGS.has(storedLang)) {
  loadDynamicBundle(storedLang);
}

// Load bundles on demand whenever the language changes
i18n.on('languageChanged', (lang) => {
  loadDynamicBundle(lang);
});

// Keep i18n in sync with stored preferences when they change elsewhere (e.g. multiple tabs)
if (typeof window !== 'undefined') {
  window.addEventListener('storage', (e) => {
    if (e.key === STORAGE_KEY && e.newValue) {
      try {
        const p = JSON.parse(e.newValue);
        if (p.language && p.language !== i18n.language) i18n.changeLanguage(p.language);
      } catch (_) {}
    }
  });
}

export default i18n;
