import React from 'react';

export const termsParagraphStyle = { fontSize: '13px', lineHeight: 1.6, color: '#334155', textAlign: 'left', paddingRight: '8px' };

const privacyLinkStyle = { background: 'rgba(255, 200, 1, 0.35)', border: 'none', padding: '0 2px', cursor: 'pointer', textDecoration: 'underline', fontWeight: '600', color: '#1e293b', fontSize: 'inherit' };

/** Terms of Service (Individuals). onOpenPrivacy is optional (e.g. open Privacy modal from within Terms). */
export function TermsOfServiceContent({ onOpenPrivacy }) {
  return (
    <div style={termsParagraphStyle}>
      <p><strong>TERMS OF SERVICE – International Property Market Platform</strong></p>
      <p><strong>Introduction.</strong> International Property Market B.V., registered with the Dutch Trade Register under number 98220136, ("IPM") offers an online platform for real estate owners, buyers, tenants, investors, brokers, agents and service providers (the "Platform"). These terms (the "Terms") govern your access to, and use of, the Platform and the services offered throughout the Platform. Please read these Terms carefully. If you do not agree to these Terms, do not use the Platform.</p>
      <p>By creating an account, accessing, or using the Platform, you ("User" or "you") acknowledge that you have read, understood, and agree to be bound by these Terms, our {onOpenPrivacy ? <button type="button" onClick={onOpenPrivacy} style={privacyLinkStyle}>Privacy Policy</button> : 'Privacy Policy'}, and any additional terms and conditions that may apply to specific features of the Platform and services offered. If you are using the Platform on behalf of a company, you represent that you have the authority to bind such company to these terms. To use the Platform, you must: be at least 18 years of age; have the legal capacity to enter into binding contracts; and comply with all applicable laws and regulations.</p>
      <p><strong>Account registration.</strong> You must create an account to access certain features of the Platform available to property owners and property buyers and tenants. You agree to provide accurate, complete, and current information during registration and to update such information to keep it accurate and current. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to immediately notify us of any unauthorized use of your account or any other breach of security. We are not liable for any loss or damage arising from your failure to protect your account credentials. We reserve the right to suspend or terminate your account at any time, with or without notice, for any reason, including but not limited to violation of these Terms, fraudulent activity, or provision of false information.</p>
      <p><strong>Services.</strong> The Platform provides a comprehensive suite of services for real estate owners as well as buyers and tenants, subject to your applicable subscription as set forth on our subscription page. We reserve the right to modify, suspend, or discontinue any aspect of the Platform or any specific service at any time, with or without notice. Different services and features may be available based on your subscription tier. We are not liable to you or any third party for any modification, suspension, or discontinuance of a service. Certain of our services may be subject to specific terms and conditions as stated, which are deemed accepted by using the services.</p>
      <p>Leads provided to you through the Platform are provided on an as-available basis. We do not guarantee the quality, quantity, or conversion rate of any leads. You must respect the privacy rights of individuals and obtain appropriate consent for communications. You may not resell, redistribute, or share leads with third parties without our express written consent. We are not responsible for the accuracy of lead information or whether leads result in actual transactions.</p>
      <p>Some of our services utilize AI systems. Our AI systems are designed with appropriate human oversight and risk mitigation measures. However, AI-generated content may contain inaccuracies and should be verified before use. You maintain sole responsibility for decisions made based on AI outputs or AI guidance. AI guidance should not replace consultation with qualified professionals such as attorneys, accountants, or licensed appraisers. AI-powered property recommendations are based on algorithms and data that may not be complete, accurate, or current. You must conduct your own due diligence on all properties, including inspections, appraisals and title searches through consultation with real estate professionals, including those on our Platform. Property information, pricing, availability, and descriptions may change without notice and should be independently verified. We do not guarantee that recommended properties will be available, accurately described, or suitable for purchase or investment. We are not a party to any real estate transactions and do not act as an agent, broker, or representative.</p>
      <p><strong>Subscription plans and service tiers.</strong> The Platform offers various subscription plans with different features, usage limits, and pricing. The specific services, features, and limitations applicable to each subscription tier are set forth on our subscription page. By subscribing to a particular plan, you agree to the terms, limitations, and pricing associated with that plan. We reserve the right to modify subscription plans, features, and pricing with reasonable notice to existing subscribers.</p>
      <p><strong>User responsibilities and prohibited conduct.</strong> You agree to comply with all applicable laws, regulations, and industry standards. You represent and warrant that all information you provide through the Platform is accurate, current, complete, and not misleading. You must have proper authorization to list any property on the Platform and possess all necessary rights to use any content you upload. You acknowledge and agree that: you are solely responsible for all investment and/or purchase decisions you make; you understand the risks associated with real estate investment, including potential losses; you will conduct appropriate due diligence before making any real estate purchase or investment; you will consult with qualified professionals as appropriate; and the Platform's services are tools to assist you, but do not replace professional advice or your own judgment.</p>
      <p>You agree not to: post false, inaccurate, misleading, defamatory, or fraudulent information; upload content that infringes intellectual property rights of others; use the Platform for any illegal or unauthorized purpose; resell, redistribute, or share leads, off-market listings, or proprietary data with third parties; breach confidentiality obligations; attempt to gain unauthorized access to the Platform or other user accounts; interfere with or disrupt the Platform; use automated systems to extract data beyond authorized use; transmit viruses or harmful code; harass, abuse, or harm other users; or impersonate any person or entity. You may not copy, modify, translate, publish, broadcast, or display any data from the Platform; reverse engineer or create derivative works of the Platform; or crawl, scrape or cache any content from the Platform.</p>
      <p><strong>Content and intellectual property.</strong> You retain all ownership rights to the content you submit to the Platform. By uploading User Content, you grant us a worldwide, non-exclusive, royalty-free, transferable, sublicensable license to use, reproduce, modify, adapt, publish, display, and distribute such content in connection with operating and promoting the Platform. The Platform, including its design, features, functionality, APIs, AI algorithms, and all content not submitted by users, is owned by us or our licensors and is protected by copyright, trademark, patent, trade secret, and other intellectual property laws. You may not copy, modify, distribute, sell, or lease any part of the Platform without our express written permission.</p>
      <p><strong>Privacy and Data Protection.</strong> Your use of the Platform is subject to our {onOpenPrivacy ? <button type="button" onClick={onOpenPrivacy} style={privacyLinkStyle}>Privacy Policy</button> : 'Privacy Policy'}. By using the Platform, you consent to our collection and use of your information as described in the Privacy Policy. You may provide sensitive financial information; we implement commercially reasonable security measures, but no system is completely secure. You are responsible for determining what information you share and for implementing appropriate security practices.</p>
      <p><strong>Fees and payment.</strong> Access to our services requires payment of subscription fees according to the plan you select. Payment is due in accordance with your billing cycle. You authorize us to charge your designated payment method. Subscriptions automatically renew unless you cancel. All fees are non-refundable unless otherwise stated or required by law. Fees are exclusive of applicable taxes. We reserve the right to change fees with reasonable notice.</p>
      <p><strong>Disclaimers &amp; liability.</strong> The Platform and all services are provided "as is" and "as available" without warranties of any kind. We do not warrant that the Platform will be uninterrupted, error-free, or secure. The Platform does not provide legal, financial, tax, or professional real estate advice. We are not responsible for the accuracy of user content, third-party content, property listings, or market data. Real estate investments involve substantial risks. To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages. Our total liability shall not exceed the amount you paid to us in the twelve (12) months preceding the claim.</p>
      <p><strong>Indemnification.</strong> You agree to indemnify, defend, and hold harmless IPM, its affiliates, officers, directors, employees and licensors from and against any claims, liabilities, damages, losses, costs, or expenses arising from your use of the Platform, your User Content, your investment decisions, your violation of these Terms, or your violation of any rights of third parties or applicable laws.</p>
      <p><strong>Termination.</strong> You may terminate your account at any time. We may suspend or terminate your account at any time, with or without cause. Upon termination, all licenses cease, you lose access to services, and we may delete your data in accordance with our policies. Provisions that by their nature should survive termination shall survive.</p>
      <p><strong>Miscellaneous.</strong> These terms may be revised by IPM at any time; you will be notified when you next login. You cannot transfer your rights or obligations without our prior written consent. Dutch law applies. Any dispute shall be submitted to the competent court in Amsterdam, the Netherlands.</p>
      <p>Contact: enquiries@internationalpropertymarket.com</p>
    </div>
  );
}

export const PRIVACY_POLICY_CONTENT = (
  <div style={termsParagraphStyle}>
    <p><strong>PRIVACY POLICY – International Property Market</strong></p>
    <p>Your use of the Platform is subject to this Privacy Policy. International Property Market B.V. ("IPM") collects, uses, and protects your personal information in connection with the Platform and the services offered.</p>
    <p>By using the Platform, you consent to our collection and use of your information as described herein. We may collect information you provide (e.g. account registration, profile, property data, preferences), usage data, device information, and cookies. We use this information to operate and improve the Platform, to provide and personalize services, to communicate with you, and to comply with legal obligations.</p>
    <p>We implement commercially reasonable security measures to protect your data. No system is completely secure; you are responsible for maintaining the confidentiality of your account credentials and for implementing appropriate security practices. We may share information with service providers, affiliates, or as required by law. We do not sell your personal information to third parties for their marketing purposes.</p>
    <p>You may have rights to access, correct, delete, or port your data depending on your jurisdiction. To exercise these rights or for any privacy-related questions, contact us at enquiries@internationalpropertymarket.com.</p>
    <p>We may update this Privacy Policy from time to time; we will notify you of material changes. Continued use of the Platform after changes constitutes acceptance of the updated Privacy Policy.</p>
    <p>Contact: enquiries@internationalpropertymarket.com</p>
  </div>
);
